name: "kit-action-express"
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Test ngrok
        uses: johnlindquist/kit-action@main
        with:
          script: "core"
      # - name: Start Server
      #   uses: johnlindquist/kit-action@main
      #   with:
      #     script: "server"
