name: "kit-action-express"
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Get Port
        id: get-port
        user: johnlindquist/kit-action@main

      - name: Display URL
        run: |
          ip=$(curl -s http://whatismyip.akamai.com/)
          echo "http://$ip:${{ steps.get-port.outputs.port }}"

        shell: bash

      - name: Start Server
        uses: johnlindquist/kit-action@main
        with:
          script: server
          args: ${{ steps.get-port.outputs.port }}
