name: "kit-action-express"
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Tunnel
        uses: johnlindquist/kit-action@main
        with:
          script: tunnel
          args: 3000

      - name: Start Server
        uses: johnlindquist/kit-action@main
        with:
          script: server
          args: 3000
